apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-kgiovaiu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-kgiovaiu:f7aeaf451a09ec08257bb6b92edb4dd40b48dbd8@sha256:dcadbb649d6908f752fbc2b0494baf49097d760ac8d240e82309aac1920921ac
          name: container-image
